services:
  web:
    build: ./backend
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
    ports:
      - "${HOST_PORT_BACKEND}:5005"
    restart: always

  frontend:
    build: ./frontend
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    volumes:
      - .:/app/public
    ports:
      - "${HOST_PORT_FRONTEND}:3005"
    depends_on:
      - web
    restart: always

