services:
  web:
    build: ./backend
    container_name: ${COMPOSE_PROJECT_NAME}_backend
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME}
      PORT: ${HOST_PORT_BACKEND}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "${HOST_PORT_BACKEND}:${HOST_PORT_BACKEND}"
    restart: always

  frontend:
    build: ./frontend
    container_name: ${COMPOSE_PROJECT_NAME}_frontend
    environment:
      PORT: ${HOST_PORT_FRONTEND}
      BACKEND_PORT: ${HOST_PORT_BACKEND}
    volumes:
      - .:/app/public
    ports:
      - "${HOST_PORT_FRONTEND}:${HOST_PORT_FRONTEND}"
    depends_on:
      - web
    restart: always
